{
  imports = [
    ./ai.nix
    ./autocomplete.nix
    ./git.nix
    ./lang.nix
    ./lsp.nix
    ./mini.nix
    ./ui.nix
    ./utility.nix
    ./filetree.nix
    ./diagnostics.nix
    ./spellcheck.nix
    ./clipboard.nix
    ./comments.nix
    ./telescope.nix
    ./theme.nix
    ./treesitter.nix
    ./notify.nix
    ./statusline.nix
    ./visuals.nix
    ./notes.nix
    ./binds.nix
    ./projects.nix
    ./dashboard.nix
    ./options.nix
  ];
}
