name: update-flake-lock

on:
  workflow_dispatch: # allows manual triggering

  schedule:
    - cron: '30 3 * * *' # daily at 9 AM IST (03:30 UTC)

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake.lock
        id: update
        uses: DeterminateSystems/update-flake-lock@main

      - name: Merge
        run: gh pr merge --auto "${{ steps.update.outputs.pull-request-number }}" --rebase
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: ${{ steps.update.outputs.pull-request-number != '' }}
